[pomodoro]
preset = "pomodoro"

tcp-host = "localhost"
tcp-port = 9999

on-server-start  = "notify-send 'ğŸ… Pomodoro' 'Server started!'"
on-server-stopping = "notify-send 'ğŸ… Pomodoro' 'Server stoppingâ€¦'"
on-server-stop  = "notify-send 'ğŸ… Pomodoro' 'Server stopped!'"

on-timer-start = "notify-send 'ğŸ… Pomodoro' 'Timer started!'"
on-timer-stop = "notify-send 'ğŸ… Pomodoro' 'Timer stopped!'"

on-work-pause = "notify-send 'ğŸ… Pomodoro' 'Timer paused!'"
