work-duration = 1500
short-break-duration = 300
long-break-duration = 900

server-started-hook  = "notify-send 'ğŸ… Pomodoro' 'Server started!'"
server-stopping-hook = "notify-send 'ğŸ… Pomodoro' 'Server stoppingâ€¦'"
server-stopped-hook  = "notify-send 'ğŸ… Pomodoro' 'Server stopped!'"

timer-started-hook = "notify-send 'ğŸ… Pomodoro' 'Timer started!'"
timer-stopped-hook = "notify-send 'ğŸ… Pomodoro' 'Timer stopped!'"

[tcp]
host = "localhost"
port = 9999
